// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAysW8hFXTY0exHPrZy2lg97_AyXh0BtZg',
    appId: '1:716875505153:web:d8420ac2f09d1e6a892a00',
    messagingSenderId: '716875505153',
    projectId: 'simarku-a8d45',
    authDomain: 'simarku-a8d45.firebaseapp.com',
    storageBucket: 'simarku-a8d45.appspot.com',
    measurementId: 'G-M1ZWB1L1R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuK-PUsoP8-p-egC8eP6wccAwHjHx-LZc',
    appId: '1:716875505153:android:14021f42510dcada892a00',
    messagingSenderId: '716875505153',
    projectId: 'simarku-a8d45',
    storageBucket: 'simarku-a8d45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnY7PpRpDpndxemOuHqRO9zLSmpZ8G30',
    appId: '1:716875505153:ios:a5e227d6ce60912a892a00',
    messagingSenderId: '716875505153',
    projectId: 'simarku-a8d45',
    storageBucket: 'simarku-a8d45.appspot.com',
    iosBundleId: 'com.example.simarku',
  );

}